runtime: nodejs16

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: .export GOOGLE_APPLICATION_CREDENTIALS="./home/petverse-dataset/petverse-423806-c784a97fc161.json
  BUCKET_NAME: dataset-model-petverse
  COLLECTION_NAME: inference-results
